# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 566)
        Form.setMinimumSize(QtCore.QSize(512, 566))
        Form.setMaximumSize(QtCore.QSize(512, 566))
        Form.setStyleSheet("QWidget{\n"
"\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.buttonGroupBox = QtWidgets.QGroupBox(Form)
        self.buttonGroupBox.setGeometry(QtCore.QRect(50, 280, 411, 261))
        self.buttonGroupBox.setStyleSheet("QGroubBox{\n"
"background-color: rgb(170, 255, 255);\n"
"\n"
"}")
        self.buttonGroupBox.setTitle("")
        self.buttonGroupBox.setObjectName("buttonGroupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.buttonGroupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 395, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.horizontalLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.numberSevenPushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.numberSevenPushButton_2.setObjectName("numberSevenPushButton_2")
        self.gridLayout_5.addWidget(self.numberSevenPushButton_2, 0, 0, 1, 1)
        self.numberEightPushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.numberEightPushButton_2.setObjectName("numberEightPushButton_2")
        self.gridLayout_5.addWidget(self.numberEightPushButton_2, 0, 1, 1, 1)
        self.numberNinePushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.numberNinePushButton_2.setObjectName("numberNinePushButton_2")
        self.gridLayout_5.addWidget(self.numberNinePushButton_2, 0, 2, 1, 1)
        self.subtractionPushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.subtractionPushButton_2.setObjectName("subtractionPushButton_2")
        self.gridLayout_5.addWidget(self.subtractionPushButton_2, 0, 3, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.buttonGroupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 395, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.horizontalLayoutWidget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.numberFourPushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.numberFourPushButton_2.setObjectName("numberFourPushButton_2")
        self.gridLayout_6.addWidget(self.numberFourPushButton_2, 0, 0, 1, 1)
        self.numberFivePushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.numberFivePushButton_2.setObjectName("numberFivePushButton_2")
        self.gridLayout_6.addWidget(self.numberFivePushButton_2, 0, 1, 1, 1)
        self.numberSixPushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.numberSixPushButton_2.setObjectName("numberSixPushButton_2")
        self.gridLayout_6.addWidget(self.numberSixPushButton_2, 0, 2, 1, 1)
        self.divisionPushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.divisionPushButton_2.setObjectName("divisionPushButton_2")
        self.gridLayout_6.addWidget(self.divisionPushButton_2, 0, 3, 1, 1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.buttonGroupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 190, 395, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.horizontalLayoutWidget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.numberOnePushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.numberOnePushButton_5.setObjectName("numberOnePushButton_5")
        self.gridLayout_7.addWidget(self.numberOnePushButton_5, 0, 0, 1, 1)
        self.numberTwoPushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.numberTwoPushButton_5.setObjectName("numberTwoPushButton_5")
        self.gridLayout_7.addWidget(self.numberTwoPushButton_5, 0, 1, 1, 1)
        self.numberThreePushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.numberThreePushButton_5.setObjectName("numberThreePushButton_5")
        self.gridLayout_7.addWidget(self.numberThreePushButton_5, 0, 2, 1, 1)
        self.multiplyPushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.multiplyPushButton_5.setObjectName("multiplyPushButton_5")
        self.gridLayout_7.addWidget(self.multiplyPushButton_5, 0, 3, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.buttonGroupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 395, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.numberOnePushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.numberOnePushButton_2.setTabletTracking(False)
        self.numberOnePushButton_2.setObjectName("numberOnePushButton_2")
        self.gridLayout_8.addWidget(self.numberOnePushButton_2, 0, 0, 1, 1)
        self.multiplyPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.multiplyPushButton.setObjectName("multiplyPushButton")
        self.gridLayout_8.addWidget(self.multiplyPushButton, 0, 3, 1, 1)
        self.numberThreePushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.numberThreePushButton_2.setObjectName("numberThreePushButton_2")
        self.gridLayout_8.addWidget(self.numberThreePushButton_2, 0, 2, 1, 1)
        self.numberTwoPushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.numberTwoPushButton_2.setObjectName("numberTwoPushButton_2")
        self.gridLayout_8.addWidget(self.numberTwoPushButton_2, 0, 1, 1, 1)
        self.screan = QtWidgets.QLineEdit(Form)
        self.screan.setGeometry(QtCore.QRect(50, 50, 411, 161))
        self.screan.setStyleSheet("QLineEdit{\n"
"background-color: rgb(213, 255, 249);\n"
" font: 75 20pt \"MS Shell Dlg 2\"; "

"}")
        self.screan.setObjectName("screan")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.numberSevenPushButton_2.setText(_translate("Form", "7"))
        self.numberEightPushButton_2.setText(_translate("Form", "8"))
        self.numberNinePushButton_2.setText(_translate("Form", "9"))
        self.subtractionPushButton_2.setText(_translate("Form", "-"))
        self.numberFourPushButton_2.setText(_translate("Form", "4"))
        self.numberFivePushButton_2.setText(_translate("Form", "5"))
        self.numberSixPushButton_2.setText(_translate("Form", "6"))
        self.divisionPushButton_2.setText(_translate("Form", "/"))
        self.numberOnePushButton_5.setText(_translate("Form", "."))
        self.numberTwoPushButton_5.setText(_translate("Form", "0"))
        self.numberThreePushButton_5.setText(_translate("Form", "="))
        self.multiplyPushButton_5.setText(_translate("Form", "+"))
        self.numberOnePushButton_2.setText(_translate("Form", "1"))
        self.multiplyPushButton.setText(_translate("Form", "X"))
        self.numberThreePushButton_2.setText(_translate("Form", "3"))
        self.numberTwoPushButton_2.setText(_translate("Form", "2"))
# import Resources_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())